python-flake8:
  stage: test
  image: python:3.6
  before_script:
    - pip install flake8
  script:
    - flake8

python-unittest:
  stage: test
  image: python:3.6
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - py.test
